spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: tongnan
    url: jdbc:mysql:///test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    port: 6379
    host: localhost
    database: 1

